### ISSUE TITLE
medaka_model param not used in CircuitSeq.nf

### ISSUE THREAD

**Issue by LArnoldt** [mckennalab/Circuitseq#10]
Thank you for this great tool!

However, I am a bit surprised to find in "./pipelines/CircuitSeq.nf" (https://github.com/mckennalab/Circuitseq/blob/main/pipelines/CircuitSeq.nf) the model used by Medaka hardcoded. 

This is the case for the processes "MedakaConsensus", "MedakaConsensusLCP", "MedakaPolish" "MedakaPolish2". I think the argument medaka_model should be provided here as -c $params.medaka_model instead of "r941_min_high_g360".

**Comment by femiliani** [comment]
That was likely my mistake, thanks for catching it. I've fixed it so that the run script parameter `medaka_model` actually does what it's supposed to do. 

Also, this is still using pre guppy 6 tools, now that Kit14 dropped (in the hopes that one day the kit14 flongles are released) I will try to update it since some tools changed how they work, and hopefully if Kit14 does what i hope it does, we will only need 1 round of polishing so that should speed things up. 

Hope you find Circuit-seq useful, and again, thanks for catching that oversight.
