### ISSUE TITLE
create a sample dataset 

### ISSUE THREAD

**Issue by aaronmck** [mckennalab/Circuitseq#4]
Downsample reads and samples to make a fast5 dataset we can share for users to test out the pipeline

**Comment by EdGreen21** [comment]
this would be great - we tried to run the pipeline but ran into some problems with the setup - it's not always entirely clear which paths are relatively to the host, and which are within the container, so a working example would be really helpful

**Comment by femiliani** [comment]
Apologies, the delay on this one is my fault. I uploaded a sample fast5 and fastq + all the other files you will need to the "example_data" directory, this way you can try running the pipeline with or without basecalling. 

I tried to clear up the path issue because I agree, its confusing. What it boils down to is that the nextflow.config file wants absolute, everything else (as far as I've tested) can be either. Also, to keep things interesting, the nextflow.config doesn't accept empty parameters. So if you are running with basecalling you have to comment/remove the two parameters for fastq/sequencing_summary. 

Hopefully that helps, if you run into any more issues please let me know.
